version: '3'
services:
  patchman:
    container_name: patchman
    image: sjafferali/patchman:latest
    environment:
      TZ: America/Los_Angeles
      SECRET_KEY: ${SECRET_KEY}
      REPORT_HOSTS: 0.0.0.0/0
      DB_TYPE: mysql
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MEMCACHED_LOCATION: cachedb:11211
    expose:
      - 80
    restart: unless-stopped
  db:
    container_name: patchman-db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DBROOTPASS}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MARIADB_MYSQL_LOCALHOST_USER: "true"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
  cachedb:
    container_name: patchman-memcached
    image: memcached:latest
    restart: unless-stopped
volumes:
  db:
