version: '3'
services:
  patchman:
    container_name: patchman
    image: sjafferali/patchman:latest
    environment:
      TZ: America/Los_Angeles
      DB_TYPE: sqlite
      SECRET_KEY: ${SECRET_KEY}
      REPORT_HOSTS: 192.168.10.0/24,192.168.60.0/24
    expose:
      - 80
    restart: unless-stopped
