version: '3'
services:
  patchman:
    container_name: patchman
    image: sjafferali/patchman:latest
    environment:
      TZ: America/Los_Angeles
      DB_TYPE: sqlite
      SECRET_KEY: ${SECRET_KEY}
      REPORT_HOSTS: 0.0.0.0/0
    expose:
      - 80
    volumes:
      - db:/var/lib/patchman/db
    restart: unless-stopped
volumes:
  db:
